package com.xiaoniu.cleanking.bean.weatherdao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xiaoniu.cleanking.bean.AppPackageNameListDB;
import com.xiaoniu.cleanking.ui.main.bean.weatherdao.WeatherCity;

import com.xiaoniu.cleanking.bean.weatherdao.AppPackageNameListDBDao;
import com.xiaoniu.cleanking.bean.weatherdao.WeatherCityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appPackageNameListDBDaoConfig;
    private final DaoConfig weatherCityDaoConfig;

    private final AppPackageNameListDBDao appPackageNameListDBDao;
    private final WeatherCityDao weatherCityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appPackageNameListDBDaoConfig = daoConfigMap.get(AppPackageNameListDBDao.class).clone();
        appPackageNameListDBDaoConfig.initIdentityScope(type);

        weatherCityDaoConfig = daoConfigMap.get(WeatherCityDao.class).clone();
        weatherCityDaoConfig.initIdentityScope(type);

        appPackageNameListDBDao = new AppPackageNameListDBDao(appPackageNameListDBDaoConfig, this);
        weatherCityDao = new WeatherCityDao(weatherCityDaoConfig, this);

        registerDao(AppPackageNameListDB.class, appPackageNameListDBDao);
        registerDao(WeatherCity.class, weatherCityDao);
    }
    
    public void clear() {
        appPackageNameListDBDaoConfig.clearIdentityScope();
        weatherCityDaoConfig.clearIdentityScope();
    }

    public AppPackageNameListDBDao getAppPackageNameListDBDao() {
        return appPackageNameListDBDao;
    }

    public WeatherCityDao getWeatherCityDao() {
        return weatherCityDao;
    }

}
